
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - default-jdk


sphinx:
  configuration: docs/user-guide/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .