version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - default-jdk
    - maven
  jobs:
    post_install:
        - pwd
        - ls -lstr
        - ls -lstr src
        - ls -lstr src/pymeter
        - mvn dependency:copy-dependencies -f java-dependencies/pom.xml
        - mkdir -p /home/docs/checkouts/readthedocs.org/user_builds/pymeter/envs/latest/lib/python3.8/site-packages/pymeter/resources/jars
        - cp java-dependencies/target/dependency/* /home/docs/checkouts/readthedocs.org/user_builds/pymeter/envs/latest/lib/python3.8/site-packages/pymeter/resources/jars
        - ls -l /home/docs/checkouts/readthedocs.org/user_builds/pymeter/envs/latest/lib/python3.8/site-packages/pymeter/resources/jars

sphinx:
  configuration: docs/user-guide/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
