version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - default-jdk
    - maven
  jobs:
    pre_install:
        - pwd
        - ls -lstr
        - ls -lstr src
        - ls -lstr src/pymeter
        - mvn dependency:copy-dependencies -f java-dependencies/pom.xml
        - mkdir -p src/pymeter/resources/jars
        - cp java-dependencies/target/dependency/* src/pymeter/resources/jars
        - ls -l src/pymeter/resources/jars

sphinx:
  configuration: docs/user-guide/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
