name: ToxTest

on:
  push:

  workflow_dispatch:

jobs:

  run_tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
      - name: install jars dependencies
      - run: mvn dependency:copy-dependencies -DoutputDirectory=./src/pymeter/resources/jars