name: run tests
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Run maven tests
        run: mvn dependency:copy-dependencies -DoutputDirectory=./src/pymeter/resources/jars -f java-dependencies/pom.xml
